title: Woomin Park
author: Woomin Park
email: park1824@purdue.edu
description: > 
  Ph.D. Student in Philosophy at Purdue University.
theme: minima
header_pages:
  - research.md
  - teaching.md
  - cv.md
